{{- if not .Values.kibana.elasticsearchAccount.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ toYaml .Values.kibana.elasticsearchAccount.secret }}
  labels:
{{ include "opendistro-es.labels.standard" . | indent 4 }}
type: Opaque
data:
    username: {{ toYaml .Values.kibana.elasticsearchAccount.username | b64enc }}
    password: {{ toYaml .Values.kibana.elasticsearchAccount.password | b64enc }}
    cookie: {{ toYaml .Values.kibana.elasticsearchAccount.cookie | b64enc }}
{{- end }}