{{- if and .Values.elasticsearch.gcs.enabled (not .Values.elasticsearch.gcs.useExistingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.elasticsearch.gcs.secretName }}
  labels:
{{ include "opendistro-es.labels.standard" . | indent 4 }}
data:
  gcs-credentials.json: |
    {{ .Values.elasticsearch.gcs.keyfileData | nindent 4 }}
{{- end }}
