{{- if .Values.elasticsearch.securityConfig.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "opendistro-es.fullname" . }}-es-config-secrets
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "opendistro-es.labels.standard" . | indent 4 }}
type: Opaque
data:
{{- if .Values.elasticsearch.securityConfig.config }}
{{- range $key, $val := .Values.elasticsearch.securityConfig.config }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end }}
{{- end }}
{{- end}}
