name: Prod Sync DATAPREPPER Artifacts

on:
  repository_dispatch:
    types: [prod-sync-data-prepper]

jobs:
  sync-dataprepper-artifacts-prod:
    name: sync-dataprepper-artifacts-prod
    runs-on: [ubuntu-18.04]
    steps:
    - uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: S3 sync artifacts
      run: |
        #!/bin/bash
        S3_BUCKET_PROD="artifacts.opendistroforelasticsearch.amazon.com"
        TARGET_DIR=`./bin/plugins-info data-prepper zip --require-install-false`
        TAG_VERSION="v$(./bin/plugins-info data-prepper cutversion --require-install-false | tr ' ' '\n' | uniq | sort -V | head -n 1)"

        echo $TAG_VERSION
        aws s3 sync s3://$S3_BUCKET_PROD/$TARGET_DIR/ s3://$S3_BUCKET_PROD/tarball/opendistroforelasticsearch-data-prepper/ --exclude "*" --include "data-prepper-jdk-${TAG_VERSION}*" --quiet
        aws s3 sync s3://$S3_BUCKET_PROD/$TARGET_DIR/ s3://$S3_BUCKET_PROD/tarball/opendistroforelasticsearch-data-prepper/ --exclude "*" --include "data-prepper-${TAG_VERSION}*" --quiet
        aws s3 ls s3://$S3_BUCKET_PROD/tarball/opendistroforelasticsearch-data-prepper/ | grep $TAG_VERSION
        aws cloudfront create-invalidation --distribution-id E1VG5HMIWI4SA2 --paths "/tarball/opendistroforelasticsearch-data-prepper/*"

